config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :authors do
    resources :books, except: [:index]
  end
  resources :books, only: [:index] do
    resources :reviews, except: [:index]
  end

  resources :users, only: [:new, :create, :show] do
    resources :suggestions, except: [:index]
  end

  resources :suggestions, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord

  has_many :books, dependent: :destroy

  validates_presence_of :name

  def self.alpha_order
    order('name ASC')
  end

  def name_switch
    name.split(',').rotate(1).join(' ')
  end

end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :author
  has_many :reviews
  has_many :users, through: :reviews

  validates_presence_of :title, :year, :image

  def self.alpha_order
    order('title ASC')
  end

  def avg_rating
    reviews.average(:rating)
  end

  def order_reviews
    reviews.order('created_at DESC')
  end
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :book
  belongs_to :user

  validates_presence_of :rating, :comment

  def time
    created_at.strftime('%b %d, %Y')
  end
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord

  belongs_to :user

  validates_presence_of :author, :title, :rating, :comment

end

app/models/user.rb
class User < ApplicationRecord

  has_many :reviews
  has_many :books, through: :reviews
  has_many :suggestions

  validates :username, uniqueness: true, presence: true
  validates_presence_of :password, require: true

  has_secure_password

  enum role: ['default', 'admin']

  def order_reviews
    reviews.order('created_at DESC')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :current_admin?

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
    @authors = Author.alpha_order
  end

  def show
    @author = Author.find(params[:id])
    @books = @author.books.alpha_order
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to author_path(@author)
    else
      render :new
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    @author.update(author_params)
    if @author.save
      redirect_to author_path(@author)
    else
      render :edit
    end
  end

  def destroy
    author = Author.find(params[:id])
    author.destroy

    redirect_to authors_path
  end

  private

  def author_params
    params.require(:author).permit(:name)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.alpha_order
  end

  def show
    @book = Book.find(params[:id])
    @reviews = @book.order_reviews
  end

  def new
    @book = Book.new
    @author = Author.find(params[:author_id])
  end

  def create
    @author = Author.find(params[:author_id])
    @book = @author.books.create(book_params)
    if @book.save
      redirect_to author_book_path(@author, @book)
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
    @author = Author.find(params[:author_id])
  end

  def update
    @author = Author.find(params[:author_id])
    @book = @author.books.find(params[:id])
    @book.update(book_params)
    if @book.save
      redirect_to author_book_path(@author, @book)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy

    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :year, :image, :author_id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
    @book = Book.find(params[:book_id])
  end

  def create
    @book = Book.find(params[:book_id])
    @review = @book.reviews.create(review_params)
    if @review.save
      redirect_to author_book_path(@book.author, @book)
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
    @book = Book.find(params[:book_id])
  end

  def update
    @book = Book.find(params[:book_id])
    @review = @book.reviews.find(params[:id])
    @review.update(review_params)
    if @review.save
      redirect_to author_book_path(@book.author, @book)
    else
      render :edit
    end
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy

    redirect_to author_book_path(review.book.author, review.book)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment, :book_id, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      #flash message - username/password combo wasn't valid
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController

  def index
    @suggestions = Suggestion.all
  end

  def new
    @suggestion = Suggestion.new
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    @suggestion = @user.suggestions.create(suggestion_params)
    if @suggestion.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    suggestion = Suggestion.find(params[:id])
    suggestion.destroy

    redirect_to suggestions_path
  end

  private

  def suggestion_params
    params.require(:suggestion).permit(:author, :title, :rating, :comment, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.order_reviews
    @suggestions = @user.suggestions
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :role)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_form.html.erb
<div class='form'>
  <%= form_for @author do |f| %>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/authors/edit.html.erb
<section>
  <% if current_user && current_admin? %>
    <h2 class='title'>Edit Author</h2>
    <%= render partial: 'form' %>
  <% else %>
    <%= render file:'/public/404' %>
  <% end %>
</section>

app/views/authors/index.html.erb
<section>
  <h1 class='title'>All Authors</h1>

  <div class='authors'>
    <% if current_user && current_admin? %>
      <p><%= link_to 'Create a New Author', new_author_path %></p>
    <% end %>

    <% @authors.each do |author| %>
      <h2><%= link_to author.name_switch, author_path(author) %></h2>
    <% end %>
  </div>
</section>

app/views/authors/new.html.erb
<section>
  <% if current_user && current_admin? %>
    <h2 class='title'>Create a New Author</h2>
    <%= render partial: 'form' %>
  <% else %>
    <%= render file:'/public/404' %>
  <% end %>
</section>

app/views/authors/show.html.erb
<section>
  <h2 class='author-name'>Books by <%= @author.name_switch %></h2>

  <% if current_user && current_admin? %>
    <p><%= link_to "Create a New Book by #{@author.name_switch}", new_author_book_path(@author) %></p>
    <p><%= link_to 'Edit Author', edit_author_path(@author) %>
    <p><%= link_to "Delete Author", author_path(@author), method: 'delete' %>
  <% end %> <br><br>

  <div class='grid'>
    <% @books.each do |book| %>
      <div class='grid-items'>
        <%= link_to (image_tag(book.image, size: '100x150', alt: 'not_available.png')), author_book_path(@author, book) %>
        <h3><%= link_to book.title, author_book_path(@author, book) %></h3><br>
      </div>
    <% end %>
  </div>
</section>

app/views/books/_form.html.erb
<div class='form'>
  <%= form_for [@author, @book] do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :year %>
      <%= f.number_field :year %>
    </div>
    <div>
      <%= f.label :image %>
      <%= f.text_field :image %>
    </div>
    <div>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<section>
  <% if current_user && current_admin? %>
    <h2 class='title'>Edit a Book by <%= @author.name_switch %></h2>
    <%= render partial: 'form' %>
  <% else %>
      <%= render file:'/public/404' %>
  <% end %>
</section>

app/views/books/index.html.erb
<section>
  <h1 class='title'>All Books</h1>

  <% @books.each do |book| %>
    <div class='book'>
      <%= link_to (image_tag(book.image, size: '125x175', alt: 'not_available.png')), author_book_path(book.author, book) %>
      <h2><%= link_to book.title, author_book_path(book.author, book) %></h2>
      <h3>by <%= link_to book.author.name_switch, author_path(book.author) %></h3>
      <% if book.avg_rating != nil %>
        <h3>Average Rating: <%= book.avg_rating %></h3>
      <% end %>
    </div>
  <% end %>
</section>

app/views/books/new.html.erb
<section>
  <% if current_user && current_admin? %>
    <h2 class='title'>Create a New Book by <%= @author.name_switch %></h2>
    <%= render partial: 'form' %>
  <% else %>
    <%= render file:'/public/404' %>
  <% end %>
</section>

app/views/books/show.html.erb
<section>
  <div class='book'>
    <%= image_tag(@book.image, size: '125x175', alt: 'not_available.png') %>
    <h2><%= @book.title %> - <%= @book.year %></h2>
    <% if @book.avg_rating != nil %>
      <h3>Average Rating: <%= @book.avg_rating %></h3>
    <% end %>
    <h3><%= link_to "See all books by #{@book.author.name_switch}", author_path(@book.author) %></h3>
  </div>

  <div class='authors'>
    <% if current_user && current_admin? %>
      <p><%= link_to 'Edit Book', edit_author_book_path(@book.author, @book) %></p>
      <p><%= link_to "Delete Book", author_book_path(@book.author, @book), method: 'delete' %></p><br>
      <h2><%= link_to 'Write a Review', new_book_review_path(@book) %></h2><br>
    <% elsif current_user %>
      <h2><%= link_to 'Write a Review', new_book_review_path(@book) %></h2><br>
    <% end %>
  </div>

  <div class='reviews'>
    <% if @reviews == [] %>
      <h3>No reviews yet - Sign in to leave a review!</h3>
    <% else %>
      <h3>Reviews (Sign in to leave a review!)</h3>
      <% @reviews.each do |review| %>
        Rating: <%= review.rating %> out of 5</br>
        Comment: <%= review.comment %></br>
        By: <%= review.user.username %></br>
        <%= review.time %></br>
        <% if current_user && current_admin? %>
          <p><%= link_to 'Edit Review', edit_book_review_path(@book, review) %></p>
          <p><%= link_to 'Delete Review', book_review_path(@book, review), method: 'delete' %></p>
        <% end %><br>
      <% end %>
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookClub</title>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Berkshire Swash' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Cagliostro' rel='stylesheet'>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <%= image_tag('bookshelf.jpg', size: '300x125') %>
      <h1 id='header'><%= link_to 'BookClub', root_path %></h1>
    </header>
    <nav>
      <h3><%= link_to 'See All Authors', authors_path %></h3>
      <h3><%= link_to 'See All Books', books_path %></h3>
      <% if current_user %>
        <h3><%= link_to "See reviews by #{current_user.username}", user_path(current_user) %></h3>
        <h3><%= link_to 'Log Out', logout_path %></h3>
      <% else %>
        <h3><%= link_to 'Sign up to be a Member', new_user_path %></h3>
        <h3><%= link_to 'Member Log In', login_path %></h3>
      <% end %>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/reviews/_form.html.erb
<div class='form'>
  <%= form_for [@book, @review] do |f| %>
    <div>
      <%= f.label :rating %>
      <%= f.select :rating, [5, 4, 3, 2, 1]%>
    </div><br>
    <div>
      <%= f.label :comment %>
      <%= f.text_area :comment, cols: 30, rows: 5 %>
      <%= f.hidden_field :user_id, value: current_user.id %>
    </div>
    <div>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<section>
  <% if current_user %>
    <h2 class='title'>Edit <%= current_user.username %>'s Review of <%= @book.title %></h2>
    <%= render partial: 'form' %>
  <% else %>
    <%= render file:'/public/404' %>
  <% end %>
</section>

app/views/reviews/new.html.erb
<section>
  <% if current_user %>
    <h2 class='title'><%= current_user.username %>'s New Review of <%= @book.title %></h2>
    <%= render partial: 'form' %>
  <% else %>
    <%= render file:'/public/404' %>
  <% end %>
</section>

app/views/suggestions/_form.html.erb
<div class='form'>
  <%= form_for [@user, @suggestion] do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :author %>
      <%= f.text_field :author %>
    </div>
    <div>
      <%= f.label :rating %>
      <%= f.select :rating, [5, 4, 3, 2, 1]%>
    </div><br>
    <div>
      <%= f.label :comment %>
      <%= f.text_area :comment, cols: 30, rows: 5 %>
    </div>
    <div>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/suggestions/index.html.erb
<section>
  <% if current_user && current_admin? %>
    <h2>All suggestions: please add to database and then delete each suggestion<h2>
    <% @suggestions.each do |suggestion| %>
      Suggestion from: <%= suggestion.user.username %><br>
      Author: <%= suggestion.author %><br>
      Title: <%= suggestion.title %><br>
      Rating: <%= suggestion.rating %><br>
      Comment: <%= suggestion.comment %><br>
      <p><%= link_to "Delete Suggestion", user_suggestion_path(current_user, suggestion), method: 'delete' %></p><br><br>
    <% end %>
  <% else %>
    <%= render file:'/public/404' %>
  <% end %>
</section>

app/views/suggestions/new.html.erb
<section>
  <% if current_user %>
    <h2 class='title'>Book Suggestion by <%= current_user.username %></h2>
    <%= render partial: 'form' %>
  <% else %>
    <%= render file:'/public/404' %>
  <% end %>
</section>

app/views/users/new.html.erb
<section>
  <h2 class='title'>Sign up to be a New Member!</h2>

  <div class='form'>
    <%= form_for @user do |f| %>
      <div>
        <%= f.label :username %>
        <%= f.text_field :username %>
      </div>
      <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div>
        <%= f.submit "Create Member" %>
      </div>
    <% end %>
  </div>
</section>

app/views/users/show.html.erb
<section>
  <% if current_user %>
    <h1 class='title'>Welcome, <%= current_user.username %>!</h1>

    <div class='user-stuff'>
      <div>
        <h2>Your reviews</h2>
        <% @reviews.each do |review| %>
          <h3>Your review of <%= link_to review.book.title, author_book_path(review.book.author, review.book) %>: </h3>
          Rating: <%= review.rating %> out of 5<br>
          Comment: <%= review.comment %></br>
          Created on: <%= review.time %></br>
          <div class='links'>
            <p><%= link_to 'Edit Review', edit_book_review_path(review.book, review) %></p>
            <p><%= link_to 'Delete Review', book_review_path(review.book, review), method: 'delete' %></p><br>
          </div>
        <% end %>
      </div>

      <div>
        <% if current_admin? %>
          <p><%= link_to 'See all suggestions', suggestions_path %></p>
        <% end %>
        <h2><%= link_to 'Make a Book Suggestion', new_user_suggestion_path(current_user) %></h2>
        <h3>Your Suggestions:</h3>
        <% @suggestions.each do |suggestion| %>
          Author: <%= suggestion.author %></br>
          Title: <%= suggestion.title %></br>
          Rating: <%= suggestion.rating %></br>
          Comment: <%= suggestion.comment %></br><br>
        <% end %>
      </div>
    </div>
  <% else %>
    <%= render file:'/public/404' %>
  <% end %>
</section>

app/views/welcome/index.html.erb
<section>
  <div class='welcome1'>
    <%= image_tag('people_reading.jpg', size: '375x250') %>
    <h3 class='title'>Welcome to BookClub</h3>
  </div><br><br><br>
  <div class='welcome2'>
    <%= image_tag('kid.jpg', size: '400x250') %>
    <h3 class='title'>Log In to leave reviews, or sign up to be a new member!</h3>
  </div>
</section>